apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gobig-api
  namespace: gobig
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 25m
spec:
  ingressClassName: nginx
  rules:
    - host: gobig-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gobig-api
                port:
                  number: 80
